server:
  port: 8084

camel:
  component:
    rabbitmq:
      hostname: localhost
      port: 5672
      username: guest
      password: guest

spring:
  application:
    name: esb-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.apache.camel: INFO
